### PR TITLE
Fix  issue with multiple text editor

### LINKED ISSUE #182: Fix opening of two text editor at once

### PR DESCRIPTION
**Pull request by 8kdesign**
Fixes #182

### CODE REVIEW

**Review by ivanchongzhien — APPROVED** [review]
Nice fix. Looks good to me

File: src/main/java/seedu/duke/editor/TextEditor.java [hunk 1]
```diff
@@ -30,32 +31,59 @@
...
+
+    //@@author 8kdesign
+    public static boolean createNew(String path, String fileName) {
+        if (textEditor == null) {
+            textEditor = new TextEditor(path, fileName);
+            textEditor.addWindowListener(new WindowAdapter() {
+                @Override
+                public void windowClosed(WindowEvent e) {
+                    super.windowClosed(e);
+                    textEditor = null;
```
Comment (H-horizon) [inline src/main/java/seedu/duke/editor/TextEditor.java:72]: Nice thinking!

**Review by H-horizon — APPROVED** [review]
LGTM
