### PR TITLE
Fix UI

### LINKED ISSUE #53: Add lines between input and output

### PR DESCRIPTION
**Pull request by 8kdesign**
Add lines to seperate sections.
Fix ModuleInfoCommand to print only undone tasks.
Remove extra line printed by module commands.

Fixes #53 #58 #61

### CODE REVIEW

File: src/main/java/seedu/duke/commands/ListModulesCommand.java [hunk 1]
```diff
@@ -18,14 +18,20 @@
...
+                stringBuilder.append(NEWLINE);
+            }
+            String moduleCode = ModuleList.getModules().get(i);
             int counter = ModuleList.getModules().indexOf(moduleCode) + 1;
             stringBuilder.append(String.format(Messages.FORMAT_LIST_ITEMS, counter, moduleCode));
-            stringBuilder.append(NEWLINE);
         }
         String listMessage = stringBuilder.toString();
-        ui.printMessage(listMessage);
+        if (listMessage.length() > 0) {
```
Comment (H-horizon) [inline src/main/java/seedu/duke/commands/ListModulesCommand.java:32]: Change 0(magic number) to a constant e.g NUMBER_OF_ARGUMENTS_FOR_LIST_COMMAND

File: src/main/java/seedu/duke/commands/ModuleInfoCommand.java [hunk 2]
```diff
@@ -40,36 +28,25 @@ public ModuleInfoCommand() {
...
     public void execute(UI ui) throws CommandException {
         Module module = ModuleList.getSelectedModule();
+        String moduleCode = module.getModuleCode();
+        ui.printMessage(String.format(FORMAT_MODULE_INFO, moduleCode));
         ArrayList<Lesson> lessonList = module.getLessonList();
-        printLessonsFromList(lessonList);
-        System.out.print(NEWLINE);
-        System.out.print(UNDONE_TASK);
+        printLessonsFromList(lessonList, ui);
+        ui.printMessage("");
```
Comment (H-horizon) [inline src/main/java/seedu/duke/commands/ModuleInfoCommand.java:35]: Can change the magic string to constant EMPTY_MESSAGE

File: src/main/java/seedu/duke/common/CommandList.java [hunk 3]
```diff
@@ -0,0 +1,12 @@
+package seedu.duke.common;
+
+public interface CommandList {
+
+    default String getWord() {
+        return "";
+    }
+
+    default String getDescription() {
+        return "";
```
Comment (H-horizon) [inline src/main/java/seedu/duke/common/CommandList.java:10]: Same as the magic string above

File: src/main/java/seedu/duke/ui/UI.java [hunk 4]
```diff
@@ -105,6 +112,21 @@ public void printTasks(ArrayList<Task> taskList, Boolean isDone) {
                 printTask(task, tasksCount);
             }
         }
+        if (tasksCount == 0) {
```
Comment (H-horizon) [inline src/main/java/seedu/duke/ui/UI.java:115]: Magic number to constant EMPTY_TASK_LIST

**Review by H-horizon — APPROVED** [review]

**Review by H-horizon — COMMENTED** [review]
LGTM
